### ISSUE TITLE
Feature request: Adapt the page so we could use curl 

### ISSUE THREAD

**Issue by dosipod** [ajotanc/wled-matrix-converter#1]
Hello, I can only open issue , as we talked in discord about this  ,There are now multiple pixel art converter for wled  and out of those we see this to be most promising due to how fast you are doing the changes . The aim is simple ( or we thought ) just use curl to manipulate the page , passing all parameters as it is done with wled api already .   We are using this source https://curl.se/docs/httpscripting.html and we are really beginners in http scripting as we learn with students on the way ( we are also trying with micro-python )  .  

This example curl "http://www.example.com/when/junk.cgi?birthyear=1905&press=OK"  is so simple but really not that easy to do unless we modify the source which is easier said then done . 

Might be you could just given us tips on how to script that from our side if the page cant be simplified any further to accept curl in a simple way ( if the name of each selector is clear to us then I think doable )   . example from node red using your page 
![image](https://github.com/ajotanc/pixelart-converter/assets/87589371/d8bd61c4-e6d8-48ea-89b8-7a60c4c63641)

**Comment by ajotanc** [comment]
> Hello, I can only open issue , as we talked in discord about this ,There are now multiple pixel art converter for wled and out of those we see this to be most promising due to how fast you are doing the changes . The aim is simple ( or we thought ) just use curl to manipulate the page , passing all parameters as it is done with wled api already . We are using this source https://curl.se/docs/httpscripting.html and we are really beginners in http scripting as we learn with students on the way ( we are also trying with micro-python ) .
> 
> This example curl "http://www.example.com/when/junk.cgi?birthyear=1905&press=OK" is so simple but really not that easy to do unless we modify the source which is easier said then done .
> 
> Might be you could just given us tips on how to script that from our side if the page cant be simplified any further to accept curl in a simple way ( if the name of each selector is clear to us then I think doable ) . example from node red using your page ![image](https://user-images.githubusercontent.com/87589371/242495590-d8bd61c4-e6d8-48ea-89b8-7a60c4c63641.png)

I think we got it! 😍
